### ISSUE TITLE
fix: change the cool thing

### ISSUE THREAD

**Issue by andrefcdias** [andrefcdias/fluentui#22]
*Description to be added*

### Packages that need migration:
- [ ] @fluentui/keyboard-keys https://github.com/andrefcdias/fluentui/issues/23
- [ ] @fluentui/priority-overflow https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-accordion https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-aria https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-avatar https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-badge https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-button https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-card https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-checkbox https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-combobox https://github.com/andrefcdias/fluentui/issues/23
- [ ] @fluentui/react-components https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-context-selector https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-dialog https://github.com/andrefcdias/fluentui/issues/26
- [ ] @fluentui/react-divider https://github.com/andrefcdias/fluentui/issues/27
- [ ] @fluentui/react-image https://github.com/andrefcdias/fluentui/issues/26
- [ ] @fluentui/react-input https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-label https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-link https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-menu https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-popover https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-portal https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-positioning https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-priority-overflow https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-provider https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-radio https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-shared-contexts https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-slider https://github.com/andrefcdias/fluentui/issues/27
- [ ] @fluentui/react-spinbutton https://github.com/andrefcdias/fluentui/issues/23
- [ ] @fluentui/react-spinner https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-storybook https://github.com/andrefcdias/fluentui/issues/26
- [ ] @fluentui/react-storybook-addon https://github.com/andrefcdias/fluentui/issues/26
- [ ] @fluentui/react-switch https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-tabs https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-tabster https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-text https://github.com/andrefcdias/fluentui/issues/26
- [ ] @fluentui/react-textarea https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-theme https://github.com/andrefcdias/fluentui/issues/24
- [ ] @fluentui/react-toolbar https://github.com/andrefcdias/fluentui/issues/23
- [ ] @fluentui/react-tooltip https://github.com/andrefcdias/fluentui/issues/25
- [ ] @fluentui/react-utilities https://github.com/andrefcdias/fluentui/issues/24
